[package]
name = "example_code"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
highs = "1.6.1"
polars = {version = "0.40.0", features = ["lazy", "csv"]}
serde = {version = "1.0.202", features = ["derive"]}
toml = "0.8.13"
